[package]
name = "cli"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
heapless = "0.7.16"
postcard = { version = "1" }
serialport = "4"
tracing = "0.1"
tracing-subscriber = "0.3"
transport = { path = "../transport" }
