[package]
name = "transport"
version = "0.2.0"
edition = "2021"

[dependencies]
postcard = "1"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dependencies.defmt]
version = "0.3"
optional = true

[features]
use-defmt = ["defmt"]
