name: Build firmware

on:
  push:
    branches:
      - "**"

jobs:
    release:
        name: Release firmware
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Cache cargo & target directories
            uses: Swatinem/rust-cache@v2
          - name: Setup rust toolchain
            uses: dtolnay/rust-toolchain@stable
            with:
               targets: thumbv6m-none-eabi
               components: llvm-tools-preview
          - name: Build firmware
            run: cargo build --release --bin firmware --target thumbv6m-none-eabi
          - name: Install binutils
            uses: baptiste0928/cargo-install@v2
            with:
                crate: cargo-binutils
          - name: Convert to hex
            run: cargo objcopy --bin firmware --release -- -O ihex firmware.hex
          - name: Publish release artifacts
            uses: actions/upload-artifact@v3
            with:
              name: firmware
              path: "target/thumbv6m-none-eabi/release/firmware"